### ISSUE TITLE
"QtGraphicalEffects" is not installed

### ISSUE THREAD

**Issue by SkyMegatrends** [Machillka/arona-sddm-login#7]
I got an error when applying a theme; here's the error: file:///usr/share/sddm/themes/Arona/Main.qml:28:1: module "QtGraphicalEffects" is not installed

My system already has QtGraphicalEffects installed: Package "qt5-qtgraphicaleffects-5.15.16-2.fc42.x86_64" is already installed.

Here is some of my system information: 

Kernel: 6.14.5-300.fc42.x86_64 arch: x86_64 bits: 64 compiler: gcc v: 15.1.1
Desktop: KDE Plasma v: 6.3.4 Distro: Fedora Linux 42 (KDE Plasma Desktop Edition)

Do you have any solutions to fix the issue?

**Comment by Machillka** [comment]
It may help you that specify the Qt dependencies version in the file `Main.qml`
```qml
import QtQuick 2.15
import QtGraphicalEffects 1.15
```

**Comment by dungdinhmanh** [comment]
i have the same issue, cause on debian 13, qtgraphicaleffects version is 5.15.15-2, using xfce desktop

**Comment by Machillka** [comment]
> > i have the same issue, cause on debian 13, qtgraphicaleffects version is 5.15.15-2, using xfce desktop
> 
> It may help u that try the branch `qt6` or replace `import QtGraphicalEffects 1.0` with `import QtGraphicalEffects 1.15` in the file `Main.qml` (line:28)

I merged the branch 'qt' to `main`

**Comment by dungdinhmanh** [comment]
i have replace with 1.15 but still can't load, so i rewrite all using qt6 qt5 compat graphicaleffects

**Comment by Machillka** [comment]
The theme from main branch have fixed this.
